CREATE TABLE details ( id VARCHAR(50) PRIMARY KEY, created_at VARCHAR(50), payment_due VARCHAR(50), description VARCHAR(50), payment_terms VARCHAR(50), client_name VARCHAR(50), client_email VARCHAR(50), status VARCHAR(50), sender_street VARCHAR(50), sender_city VARCHAR(50), sender_post_code VARCHAR(50), sender_country VARCHAR(50), client_street VARCHAR(50), client_city VARCHAR(50), client_post_code VARCHAR(50), client_country VARCHAR(50), item_name VARCHAR(50), item_quantity VARCHAR(50), item_price VARCHAR(50), total VARCHAR(50));

INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('RT3080','2021-08-18', '2021-08-19', 'Re-branding', 1, 'Jensen Huang', 'jensenh@mail.com','paid', '19 Union Terrace','London','E1 3EZ','United Kingdom','106 Kendell Street','Sharrington','NR24 5WQ', 'United Kingdom', 'Brand Guidelines',1,1800.9, 1800.9);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('RG0314', '2021-09-24', '2021-10-01', 'Website Redesign', 7, 'John Morrison', 'jm@myco.com', 'paid', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '79 Dover Road', 'Westhall', 'IP19 3PF', 'United Kingdom', 'Website Redesign', 1, 14002.33, 14002.33);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('XM9141', '2021-08-21', '2021-09-20', 'Graphic Design', 30, 'Alex Grim', 'alexgrim@mail.com', 'pending', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '84 Church Way', 'Bradford', 'BD1 9PB', 'United Kingdom', 'Email Design', 2, 200.0, 400.0);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('RT2080', '2021-10-11', '2021-10-12', 'Logo Concept', 1, 'Alysa Werner', 'alysa@email.co.uk', 'pending', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '63 Warwick Road', 'Carlisle', 'CA20 2TG', 'United Kingdom', 'Logo Sketches', 1, 102.04, 102.04);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('AA1449', '2021-10-7', '2021-10-14', 'Re-branding', 7, 'Mellisa Clarke', 'mellisa.clarke@example.com', 'pending', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '46 Abbey Row', 'Cambridge', 'CB5 6EG', 'United Kingdom', 'New Logo', 1, 1532.33, 1532.33);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('TY9141', '2021-10-01', '2021-10-31', 'Landing Page Design', 30, 'Thomas Wayne', 'thomas@dc.com', 'pending', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '3964  Queens Lane', 'Gotham', '60457', 'United States of America', 'Web Design', 1, 6155.91, 6155.91);
INSERT INTO details ( id, created_at, payment_due, description, payment_terms, client_name, client_email, status, sender_street, sender_city, sender_post_code, sender_country, client_street, client_city, client_post_code, client_country, item_name, item_quantity, item_price, total) VALUES ('FV2353', '2021-11-05', '2021-11-12', 'Logo Re-design', 7, 'Anita Wainwright', '', 'draft', '19 Union Terrace', 'London', 'E1 3EZ', 'United Kingdom', '', '', '', '', 'Logo Re-design', 1, 3102.04, 3102.04);


CREATE TABLE backup_details AS TABLE details;