const style = {
  "& .MuiOutlinedInput-root:hover": {
    "& > fieldset": {
      borderColor: "#7C5DFA",
    },
  },
};

const styles = {
  1: {
    display: "flex",
    flexDirection: { xs: "column", sm: "column", md: "row" },
    paddingLeft: 0,
    bgcolor: "#F8F8FB",
  },
  2: {
    width: "100vw",
    height: "100%",
    bgcolor: "#F8F8FB",
    margin: "0",
    paddingLeft: "0",
  },
  3: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
  },
  4: {
    // padding: "1rem 2rem",
    // border: "3px solid green",
    display: { md: "flex" },
    justifyContent: "center",
    maxWidth: { sm: "700px", md: "1200px" },
    minWidth: { md: "900px" },
    margin: 0,
    padding: 0,
    overflowY: "hidden",
  },
  5: {
    minWidth: { sm: "380px", md: "760px" },
    maxWidth: { sm: "672px", md: "920px" },
    // border: "2px solid orange",
  },
  6: {
    // border: "2px dashed orange",
    height: "100%",
    margin: "2rem 7rem",
    maxWidth: { xs: "425px", sm: "800px" },
    minWidth: { xs: "300px", sm: "675px" },
    display: "flex",
    justifyContent: "center",
  },
  7: {
    textTransform: "none",
    marginLeft: "-3px",
    padding: 0,
    marginBottom: "2rem",
  },
  8: {
    color: "#7C5DFA",
    transform: "scale(0.6)",
    stroke: "#7C5DFA",
    strokeWidth: 2,
  },
  9: {
    fontSize: ".91rem",
    fontWeight: 700,
    color: "#0C0E16",
  },
  10: {
    maxWidth: "920px",
    minHeight: "75px",
    marginBottom: "1rem",
    marginX: { xs: "35px", sm: 0 },
    border: "none",
    boxShadow: "0px 10px 10px -10px rgba(72, 84, 159, 0.100397)",
  },
  11: {
    display: { xs: "grid", sm: "flex" },
    justifyContent: { sm: "space-around" },
    alignItems: "baseline",
  },
  12: {
    fontSize: { xs: "1rem", sm: ".75rem" },
    fontWeight: 700,
    minWidth: { sm: "65px" },
  },
  13: {
    fontSize: { xs: ".75rem", sm: ".75rem" },
    fontWeight: 500,
    color: "#888EB0",
    minWidth: { sm: "120px" },
    marginTop: { xs: "25px" },
  },
  14: {
    fontSize: { xs: ".91rem", sm: ".75rem" },
    fontWeight: 500,
    color: "#888EB0",
    minWidth: { sm: "100px" },
    textAlign: { xs: "right", sm: "left" },
  },
  15: {
    fontSize: "1rem",
    fontWeight: 700,
    minWidth: "95px",
    textAlign: { xs: "left", sm: "right" },
    marginBottom: { xs: 0, sm: "4.6px" },
    marginTop: { xs: "7px", sm: "1px" },
  },
  16: {
    padding: "0.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    minWidth: { xs: "100px", sm: "105px" },
    maxWidth: { xs: "200px", sm: "105px" },
  },
  17: {
    transform: "scale(0.5)",
    marginBottom: "0.2rem",
    marginRight: "0.2rem",
  },
  18: {
    fontSize: ".75rem",
    fontWeight: 700,
    minWidth: "55px",
    // border: "2px solid red",
    // bgcolor: "red",
  },
  19: {
    color: "#7C5DFA",
    transform: "scale(0.6)",
    stroke: "#7C5DFA",
    strokeWidth: 2,
    display: { xs: "none", sm: "inline" },
  },
  20: {
    minWidth: { sm: "390px", md: "500px" },
    maxWidth: { sm: "672px", md: "845px" },
  },
  21: {
    display: "flex",
    justifyContent: "space-between",
    // border: "2px dashed red",
    minWidth: { sm: "390px" },
    maxWidth: { sm: "672px", md: "920px" },
    margin: "3rem 0",
    marginTop: { md: "5rem" },
    padding: { xs: "0rem 2.25rem", sm: 0 },
  },
  22: {
    marginY: { xs: "4px", sm: 0 },
    fontSize: { xs: "1.25rem", sm: "2rem" },
    fontWeight: 700,
    color: "#0C0E16",
    letterSpacing: "-1px",
  },
  23: {
    color: "#888EB0",
    fontSize: { xs: ".75rem", sm: ".91rem" },
    fontWeight: 500,
  },
  24: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  25: {
    transform: "scale(2)",
    marginRight: "1.3rem",
    marginLeft: "0.4rem",
  },
  26: {
    position: "fixed",
    bottom: { xs: "15px", sm: "20px" },
    left: "32px",
  },
  27: {
    bgcolor: "white",
    minWidth: { xs: "95vw", sm: "660px", md: "700px" },
    maxWidth: { xs: "100vw", sm: "699px", md: "999px" },
    height: "100%",
    // padding: " .0rem 3.2rem",
    // border: "2px solid purple",
    padding: { xs: ".5rem 3.2rem 0.5rem 3.2rem", sm: "2.5rem 3.2rem" },
  },
  28: {
    fontSize: "2rem",
    fontWeight: 700,
    marginBottom: { xs: "20px", sm: "1.5rem" },
    marginTop: "2rem",
    color: "#0c0e16",
  },
  29: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "space-between",
    marginBottom: { xs: "7px", sm: "20px" },
  },
  30: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#7C5DFA",
    mb: { xs: "5px", sm: "15px" },
  },
  31: {
    color: "#7E88C3",
    marginBottom: "8px",
    fontWeight: 500,
  },
  32: {
    ...style,
    width: "100%",
  },
  33: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
  },
  34: {
    color: "#7E88C3",
    marginBottom: "10px",
    fontWeight: 500,
  },
  35: {
    ...style,
    width: "100%",
  },
  36: {
    mt: { xs: "2px", sm: "17px" },
    width: { xs: "46%", sm: "30%" },
  },
  37: {
    color: "#7E88C3",
    marginBottom: "10px",
    fontWeight: 500,
  },
  38: {
    ...style,
    width: "100%",
  },
  39: {
    width: { xs: "100%", sm: "30%" },
    mt: { xs: "10px", sm: "17px" },
  },
  40: {
    color: "#7E88C3",
    marginBottom: "10px",
    fontWeight: 500,
  },
  41: {
    ...style,
    width: "100%",
  },
  42: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minHeight: "500px",
    mb: { xs: 0, sm: "1.5rem" },
  },
  43: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#7C5DFA",
    mb: 0,
  },
  44: {
    color: "#7E88C3",
    marginBottom: "10px",
    fontWeight: 500,
  },
  45: {
    color: "#7E88C3",
    marginBottom: "10px",
    fontWeight: 500,
  },
  46: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
  },
  47: {
    mt: { xs: "2px", sm: "17px" },
    width: { xs: "46%", sm: "30%" },
  },
  48: {
    width: { xs: "100%", sm: "30%" },
    mt: { xs: "10px", sm: "17px" },
  },
  49: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "17px",
  },
  50: {
    marginTop: "5px",
    width: { xs: "110%", sm: "240px" },
  },
  51: {
    marginTop: "5px",
    width: { xs: "100%", sm: "240px" },
  },
  52: {
    mt: "5px",
    width: { xs: "100%", sm: "100%" },
  },
  53: {
    color: "#7E88C3",
    // marginBottom: "20px",
    fontWeight: 500,
    marginBottom: "12px",
  },
  54: {
    color: "#777f98",
    fontWeight: 700,
    fontSize: "1.2rem",
  },
  55: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "120px",
  },
  56: {
    width: { xs: "100%", sm: "40%" },
    marginTop: "17px",
  },
  57: {
    marginTop: "17px",
    width: { xs: "25%", sm: "10%" },
  },
  58: {
    marginTop: "17px",
    width: { xs: "37.5%", sm: "20%" },
  },
  59: {
    marginTop: "6px",
    minHeight: { xs: "102px" },
    width: { xs: "30%", sm: "20%" },
  },
  60: {
    color: "#7E88C3",
    mb: { xs: "23px", sm: "23px" },
    fontWeight: 500,
  },
  61: {
    maxWidth: "90px",
    border: "none",
    pointerEvents: "none",
  },
  62: {
    position: "fixed",
    bottom: "0px",
    left: "0px",
    height: { xs: "90px", sm: "100px" },
    paddingY: "25px",
    minWidth: { sm: "660px", md: "700px" },
    bgcolor: "#F8F8FB",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  63: {
    display: "flex",
    justifyContent: "flex-end",
    paddingX: "2rem",
  },
  64: {
    width: { xs: "90vw" },
    maxWidth: { xs: "90vw", sm: "632px", md: "850px" },
    display: "flex",
    justifyContent: "flex-end",
  },
  65: {
    bgcolor: "white",
    minWidth: { xs: "95vw", sm: "660px", md: "700px" },
    maxWidth: { xs: "100vw", sm: "699px", md: "999px" },
    padding: { xs: ".5rem 3.2rem 2.5rem 3.2rem", sm: "2.5rem 3.2rem" },
  },
  66: {
    fontSize: "2rem",
    fontWeight: 700,
    marginBottom: { xs: "20px", sm: "1.5rem" },
    marginTop: "2rem",
  },
  67: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "space-between",
    marginBottom: { xs: "7px", sm: "20px" },
  },
  68: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#7C5DFA",
    mb: { xs: "10px", sm: "15px" },
  },
  69: { color: "#7E88C3", mb: "8px", fontWeight: 500 },
  70: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
  },
  71: {
    width: { xs: "100%", sm: "30%" },
    mt: { xs: "0px", sm: "17px" },
  },
  72: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minHeight: "500px",
    mb: { xs: 0, sm: "1.5rem" },
  },
  73: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#7C5DFA",
    mb: 0,
  },
  74: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
  },
  75: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "17px",
  },
  76: {
    marginTop: "17px",
    width: { xs: "100%", sm: "260px", md: "340px" },
  },
  77: {
    color: "#7E88C3",
    // marginBottom: "20px",
    fontWeight: 500,
    marginBottom: "12px",
  },
  78: {
    color: "#777f98",
    fontWeight: 700,
    fontSize: "1.2rem",
  },
  79: {
    display: "flex",
    flexWrap: { xs: "wrap", sm: "nowrap" },
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "80px",
  },
  80: {
    marginTop: "0px",
    minHeight: { xs: "102px" },
    width: { xs: "30%", sm: "20%" },
  },
  // 80: {

  // },
  81: {
    color: "#7E88C3",
    mb: { xs: "22px", sm: "22px" },
    fontWeight: 500,
    mt: "4px",
  },
  82: {
    ...style,
    maxWidth: "90px",
  },
  83: {
    position: "fixed",
    bottom: "0px",
    left: "0px",
    height: { xs: "90px", sm: "100px" },
    minWidth: { sm: "660px", md: "700px" },
    maxWidth: { xs: "100vw", sm: "699px", md: "999px" },
    bgcolor: "#F8F8FB",
    justifyContent: "flex-end",
  },
  84: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: { xs: "15px", sm: "15px" },
    paddingX: "2rem",
    width: { xs: "100vw" },
    maxWidth: { xs: "100vw", sm: "697px", md: "915px" },
    marginBottom: { xs: "8px", sm: "50px" },
  },
  85: {
    marginTop: "2rem",
    bgcolor: "white",
    borderRadius: "10px",
    padding: { xs: "0rem 1.5rem", sm: "1rem 3rem" },
    boxShadow: "0px 10px 10px -10px rgba(72, 84, 159, 0.100397)",
    // border: "2px dashed blue",
    mb: { xs: "4rem", sm: "2rem" },
    mt: { xs: "-10px", sm: "0" },
  },
  86: {
    fontSize: ".91rem",
    fontWeight: 500,
    color: "#888EB0",
  },
  87: {
    fontSize: ".69rem",
    fontWeight: 500,
    color: "#888EB0",
    textAlign: { xs: "left", sm: "right" },
    lineHeight: "18px",
  },
  88: {
    fontSize: ".75rem",
    fontWeight: 500,
    color: "#888EB0",
    marginBottom: "10px",
  },
  89: {
    fontSize: "1rem",
    fontWeight: 700,
    marginBottom: "25px",
  },
  90: {
    fontSize: ".69rem",
    fontWeight: 500,
    color: "#888EB0",
    lineHeight: "18px",
  },
  91: {
    bgcolor: "#F9FAFE",
    // paddingTop: 0,
    margin: "0 auto",
    paddingX: { xs: "1rem", sm: "2rem" },
    paddingBottom: "2rem",
    paddingTop: "1.5rem",
    borderRadius: "8px 8px 0px 0px",
    // border: "2px solid blue",
    minWidth: "300px",
  },
  92: {
    bgcolor: "#373B53",
    paddingTop: 0,
    margin: "0 auto",
    width: { xs: "100%" },
    padding: "1.5rem 2rem",
    borderRadius: "0px 0px 8px 8px",
  },
  93: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "30px",
    bgcolor: "white",
    borderRadius: "8px",
    boxShadow: "0px 10px 10px -10px rgba(72, 84, 159, 0.100397)",
    padding: { xs: ".33rem 1.5rem", sm: "1.33rem 2rem" },
  },
  94: {
    display: "flex",
    width: { xs: "100%", sm: "29%" },
    justifyContent: "space-between",
    alignItems: "center",
    // border: "2px solid green",
  },
  95: {
    display: "flex",
    alignItems: "center",
    textTransform: "none",
    fontWeight: 500,
    fontSize: ".75rem",
    color: "#7E88C3",
    bgcolor: "white",
    borderRadius: { xs: 0, sm: "34px" },
    boxShadow: "none",
    padding: { xs: "1rem 0", sm: "1rem 0" },
    mr: "20px",
  },
  96: {
    fontSize: ".75rem",
    fontWeight: 700,
    letterSpacing: "-.25px",
  },
  97: {
    padding: "0.25rem .5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    minWidth: "105px",
    // border: "2px solid green",
    maxHeight: "40px",
  },
  98: {
    transform: "scale(0.5)",
    marginBottom: "0.2rem",
    marginRight: "0.2rem",
  },
  99: {
    display: "flex",
    alignItems: "center",
    justifyContent: { xs: "center", md: "flex-end" },
    position: { xs: "fixed", sm: "static" },
    bottom: "0px",
    left: "0px",
    // border: "2px solid red",
    minWidth: { xs: "100vw", sm: "300px", md: "310px" },
    maxWidth: { xs: "100vw", sm: "355px", md: "375px" },
    minHeight: "75px",
    maxHeight: "85px",
    bgcolor: { xs: "white" },
    padding: { xs: "0 2rem", sm: 0 },
  },
  100: {
    fontSize: ".75rem",
    padding: "1rem 1.5rem",
    letterSpacing: "-.25px",
    maxHeight: "55px",
  },
  101: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "480px",
    maxWidth: { xs: "325px", sm: "480px" },
    bgcolor: "background.paper",
    border: "none",
    boxShadow: "0px 10px 10px -10px rgba(72, 84, 159, 0.100397)",
    borderRadius: "8px",
    p: 4,
  },
  102: {
    fontSize: ".75rem",
    fontWeight: 500,
    color: "#888EB0",
    textAlign: "left",
    lineHeight: "18px",
    mb: "15px",
  },
  103: {
    fontSize: "1.5rem",
    fontWeight: 700,
    mb: "10px",
  },
  104: {
    fontSize: ".75rem",
    fontWeight: 700,
    color: "#0C0E16",
  },
  105: {
    fontSize: ".75rem",
    fontWeight: 700,
    color: "#888EB0",
    marginTop: { xs: "-10px", sm: 0 },
  },
  106: {
    fontSize: ".75rem",
    fontWeight: 700,
    color: "#888EB0",
    textAlign: { xs: "left", sm: "right" },
    marginTop: { xs: "-10px", sm: 0 },
  },
  107: {
    fontSize: ".75rem",
    fontWeight: 700,
    color: "#0C0E16",
    marginBottom: "-10px",
    // border: "2px solid pink",
    marginTop: { xs: "-20px", sm: 0 },
  },
  108: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: { xs: "235px", sm: "100%" },
    margin: 0,
    padding: 0,
    // border: "2px dashed white",
  },
  109: {
    fontSize: ".75rem",
    fontWeight: 500,
    color: "white",
    letterSpacing: "-0.33px",
    mr: "55px",
  },
  110: {
    fontSize: "1.33rem",
    fontWeight: 700,
    color: "white",
  },
  111: {
    backgroundColor: "#373B53",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    margin: 0,
  },
  112: {
    backgroundColor: "#373B53",
    position: "fixed",
    top: "0px",
    bottom: "0px",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    alignItems: "center",
  },
  113: {
    mb: "20px",
    mr: "20px",
  },
  114: {
    mr: { md: "50px" },
  },
};

// const gary = {
//   one: 1,
//   two: 2,
//   three: 4,
//   five: 5,
// };

export default styles;
